# Generated by Django 4.2.9 on 2026-03-29 16:27

import django.core.validators
from django.db import migrations, models


def mark_existing_fights_as_accepted(apps, schema_editor):
    FightRecord = apps.get_model("fight_app", "FightRecord")
    FightRecord.objects.all().update(challenge_status="accepted", duration_minutes=60)


def revert_existing_fights_to_pending(apps, schema_editor):
    FightRecord = apps.get_model("fight_app", "FightRecord")
    FightRecord.objects.all().update(challenge_status="pending")


class Migration(migrations.Migration):

    dependencies = [
        ("fight_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fightrecord",
            options={
                "ordering": ["-date", "-created_at"],
                "verbose_name": "Запись о бое",
                "verbose_name_plural": "Записи о боях",
            },
        ),
        migrations.AddField(
            model_name="fighterprofile",
            name="height_cm",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(120),
                    django.core.validators.MaxValueValidator(250),
                ],
                verbose_name="Рост (см)",
            ),
        ),
        migrations.AddField(
            model_name="fightrecord",
            name="challenge_status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает ответа"),
                    ("accepted", "Принят"),
                    ("declined", "Отклонен"),
                ],
                default="pending",
                max_length=16,
                verbose_name="Статус вызова",
            ),
        ),
        migrations.AddField(
            model_name="fightrecord",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                default=60,
                validators=[
                    django.core.validators.MinValueValidator(15),
                    django.core.validators.MaxValueValidator(300),
                ],
                verbose_name="Длительность тренировки (мин)",
            ),
        ),
        migrations.AlterField(
            model_name="fightrecord",
            name="is_finished",
            field=models.BooleanField(default=False, verbose_name="Завершен"),
        ),
        migrations.AlterField(
            model_name="fightrecord",
            name="is_sparring",
            field=models.BooleanField(default=True, verbose_name="Спарринг"),
        ),
        migrations.RunPython(mark_existing_fights_as_accepted, revert_existing_fights_to_pending),
    ]
