# Generated by Django 4.2.9 on 2026-03-29 15:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название зала')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.CreateModel(
            name='MartialArtRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('number_of_rounds', models.PositiveIntegerField(default=3, verbose_name='Количество раундов')),
                ('round_duration_minutes', models.PositiveIntegerField(default=3, verbose_name='Длительность раунда (мин)')),
            ],
            options={
                'verbose_name': 'Правила вида спорта',
                'verbose_name_plural': 'Правила видов спорта',
            },
        ),
        migrations.CreateModel(
            name='FightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата боя')),
                ('is_sparring', models.BooleanField(default=True, verbose_name='Спарринг (без победителя)')),
                ('opponent_review', models.TextField(blank=True, verbose_name='Отзыв об оппоненте')),
                ('opponent_skill_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка навыков соперника (1-10)')),
                ('rating_delta', models.IntegerField(default=0, verbose_name='Изменение рейтинга')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Завершён')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_fights', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fight_app.location', verbose_name='Локация')),
                ('martial_art_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fight_app.martialartrule', verbose_name='Правила')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent_fights', to=settings.AUTH_USER_MODEL, verbose_name='Оппонент')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_fights', to=settings.AUTH_USER_MODEL, verbose_name='Победитель')),
            ],
            options={
                'verbose_name': 'Запись о бое',
                'verbose_name_plural': 'Записи о боях',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FighterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1000, verbose_name='Рейтинг')),
                ('experience_level', models.IntegerField(choices=[(1, 'Новичок'), (2, 'Любитель'), (3, 'Средний'), (4, 'Продвинутый'), (5, 'Профессионал')], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Уровень опыта')),
                ('achievements', models.TextField(blank=True, verbose_name='Достижения')),
                ('weight_kg', models.FloatField(blank=True, null=True, verbose_name='Вес (кг)')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('avatar_url', models.URLField(blank=True, verbose_name='Аватар')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fighter_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль бойца',
                'verbose_name_plural': 'Профили бойцов',
            },
        ),
    ]
