# Generated by Django 5.2.1 on 2026-03-28 07:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forward_migrate_challenges(apps, schema_editor):
    FighterExperience = apps.get_model('fights', 'FighterExperience')
    FighterProfile = apps.get_model('fights', 'FighterProfile')
    FighterReview = apps.get_model('fights', 'FighterReview')
    FightRecord = apps.get_model('fights', 'FightRecord')
    MartialArtRule = apps.get_model('fights', 'MartialArtRule')
    User = apps.get_model('auth', 'User')

    FightRecord.objects.exclude(result__in=['pending', 'accepted', 'declined', 'cancelled']).update(result='accepted')

    fighter_one = User.objects.filter(username='fighter_one').first()
    fighter_two = User.objects.filter(username='fighter_two').first()

    if not fighter_one or not fighter_two:
        return

    boxing = MartialArtRule.objects.filter(name='Boxing').first()
    mma = MartialArtRule.objects.filter(name='MMA').first()
    kickboxing = MartialArtRule.objects.filter(name='Kickboxing').first()

    fighter_one_profile = FighterProfile.objects.filter(user=fighter_one).first()
    fighter_two_profile = FighterProfile.objects.filter(user=fighter_two).first()

    if fighter_one_profile and boxing:
        FighterExperience.objects.get_or_create(
            profile=fighter_one_profile,
            martial_art_rule=boxing,
            defaults={'years': 1, 'months': 3},
        )

    if fighter_two_profile and kickboxing:
        FighterExperience.objects.get_or_create(
            profile=fighter_two_profile,
            martial_art_rule=kickboxing,
            defaults={'years': 2, 'months': 1},
        )

    if fighter_two_profile and mma:
        FighterExperience.objects.get_or_create(
            profile=fighter_two_profile,
            martial_art_rule=mma,
            defaults={'years': 0, 'months': 8},
        )

    FighterReview.objects.get_or_create(
        reviewer=fighter_one,
        target=fighter_two,
        defaults={'rating': 4, 'comment': 'Shows up on time and keeps sparring respectful.'},
    )
    FighterReview.objects.get_or_create(
        reviewer=fighter_two,
        target=fighter_one,
        defaults={'rating': 5, 'comment': 'Technical boxer, good pace and discipline.'},
    )

    for profile in FighterProfile.objects.all():
        accepted_total = FightRecord.objects.filter(
            models.Q(initiator=profile.user, result='accepted') | models.Q(opponent=profile.user, result='accepted')
        ).count()
        reviews = FighterReview.objects.filter(target=profile.user)
        total_reviews = reviews.count()
        average_score = sum(review.rating for review in reviews) / total_reviews if total_reviews else 0

        profile.total_fights = accepted_total
        profile.total_reviews = total_reviews
        profile.average_review_score = round(average_score, 2)
        profile.rating = int(average_score * 20)
        profile.save(update_fields=['total_fights', 'total_reviews', 'average_review_score', 'rating'])


class Migration(migrations.Migration):

    dependencies = [
        ('fights', '0002_seed_demo_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fighterprofile',
            options={'ordering': ['-rating', '-average_review_score', 'user__username']},
        ),
        migrations.AddField(
            model_name='fighterprofile',
            name='average_review_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='fighterprofile',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fightrecord',
            name='message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fighterprofile',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fightrecord',
            name='result',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='FighterExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.PositiveSmallIntegerField(default=0)),
                ('months', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(11)])),
                ('martial_art_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fighter_experiences', to='fights.martialartrule')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='fights.fighterprofile')),
            ],
            options={
                'ordering': ['-years', '-months', 'martial_art_rule__name'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'martial_art_rule'), name='unique_fighter_experience')],
            },
        ),
        migrations.CreateModel(
            name='FighterReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('reviewer', models.F('target')), _negated=True), name='reviewer_and_target_must_be_different'), models.UniqueConstraint(fields=('reviewer', 'target'), name='unique_fighter_review_pair')],
            },
        ),
        migrations.RunPython(forward_migrate_challenges, migrations.RunPython.noop),
    ]
